version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fs_exp_9
    ports:
      - "3307:3306"

  backend:
    build: ./backend
    container_name: spring-backend
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fs_exp_9?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "80:80"
    depends_on:
      - backend