name: Backend CI (Spring Boot)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    # We force the runner to use Node 24 to fix that warning
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Grant execute permission for mvnw
      run: chmod +x backend/mvnw

    - name: Build with Maven
      # We run the command from the root but point it to the backend folder
      run: ./backend/mvnw clean package -DskipTests backend/pom.xml